
from typing import Protocol, Tuple, List

class VNA(Protocol):
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def sweep_s11(self, start_hz: float, stop_hz: float, points: int = 201) -> Tuple[List[float], List[float]]: ...
    def sweep_s21(self, start_hz: float, stop_hz: float, points: int = 201) -> Tuple[List[float], List[float]]: ...
    # Spectrum helpers for linearity/harmonics
    def sa_config(self, center_hz: float, span_hz: float, rbw_hz: float, vbw_hz: float|None=None) -> None: ...
    def sa_marker_read(self, freqs: List[float]) -> List[float]: ...
    def screenshot(self, path: str) -> None: ...
