
pgxl:
  host: "192.168.0.33"
  port: 9007
  model: "PGXL"
flex:
  host: "192.168.0.20"
  port: 4992
vna:
  vendor: "rigol"
  visa:
    resource: "TCPIP0::vna.rigol.internal::5025::SOCKET"
    timeout_ms: 5000
bands_m: [160,80,60,40,30,20,17,15,12,10,6]
